---
- name: install and start httpd service
  hosts: webservers
  user: fedora
  sudo: yes
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: Ensure http server installed
    yum: name=httpd state=present
  - name: Start http server service
    service: name=httpd state=started
  - name: Enable service from firewalld
    firewalld: service=http permanent=true state=enabled
